# Define here the models for your scraped items
#
# See documentation in:
# http://doc.scrapy.org/topics/items.html

from scrapy.item import Item, Field

class Website(Item):
    name = Field()
    description = Field()
    gallery0 = Field()

class Board(Item):
    content = Field()
    price = Field()
    old_price = Field()
    pagetitle = Field()
    weight = Field()
    image = Field()
    color = Field()
    size = Field()
    url0 = Field()
    url1 = Field()
    url2 = Field()
    url3 = Field()
    url4 = Field()
    url5 = Field()
    url6 = Field()
    url7 = Field()
    url8 = Field()
    url9 = Field()
    url10 = Field()
    url11 = Field()
    url12 = Field()
    url13 = Field()
    url14 = Field()
    url15 = Field()
    url16 = Field()
    url17 = Field()
    url18 = Field()
    url19 = Field()
    url20 = Field()
    url21 = Field()
    url22 = Field()
    url23 = Field()
    url24 = Field()
    url25 = Field()
    url26 = Field()
    url27 = Field()
    url28 = Field()
    url29 = Field()
    url30 = Field()
    url31 = Field()
    url32 = Field()
    url33 = Field()
    url34 = Field()
    url35 = Field()
    url36 = Field()
    url37 = Field()
    url38 = Field()
    url39 = Field()
    url40 = Field()
    url41 = Field()
    url42 = Field()
    gallery0 = Field()
    gallery1 = Field()
    gallery2 = Field()
    gallery3 = Field()
    gallery4 = Field()
    gallery5 = Field()
    gallery6 = Field()
    gallery7 = Field()
    gallery8 = Field()
    gallery9 = Field()
    gallery10 = Field()
    gallery11 = Field()
    gallery12 = Field()
    gallery13 = Field()
    gallery14 = Field()
    gallery15 = Field()
    gallery16 = Field()
    gallery17 = Field()
    gallery18 = Field()
    gallery19 = Field()
    gallery20 = Field()
    gallery21 = Field()
    gallery22 = Field()
    gallery23 = Field()
    gallery24 = Field()
    gallery25 = Field()
    gallery26 = Field()
    gallery27 = Field()
    gallery28 = Field()
    gallery29 = Field()
    gallery30 = Field()
    gallery31 = Field()
    gallery32 = Field()
    gallery33 = Field()
    gallery34 = Field()
    gallery35 = Field()
    gallery36 = Field()
    gallery37 = Field()
    gallery38 = Field()
    gallery39 = Field()
    gallery40 = Field()
    gallery41 = Field()
    gallery42 = Field()


    name = Field()
    boatyear = Field()
    boatbrand = Field()
    boatmodel = Field()
    boatlength = Field()
    boatwidth = Field()
    boatmotor = Field()
    boattype = Field()
